/* eslint-disable */

// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/dashboard";
import { Route as AuthenticatedGithubRouteImport } from "./routes/_authenticated/github";
import { Route as AuthenticatedNotesRouteImport } from "./routes/_authenticated/notes";
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile";
import { Route as AuthenticatedProjectsRouteImport } from "./routes/_authenticated/projects";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings";
import { Route as AuthenticatedCoursesIndexRouteImport } from "./routes/_authenticated/courses.index";
import { Route as AuthenticatedCoursesNewRouteImport } from "./routes/_authenticated/courses.new";
import { Route as AuthenticatedCourseCourseIdIndexRouteImport } from "./routes/_authenticated/course.$courseId.index";
import { Route as AuthenticatedCourseCourseIdLessonLessonIdRouteImport } from "./routes/_authenticated/course.$courseId.lesson.$lessonId";
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedGithubRoute = AuthenticatedGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedCoursesIndexRoute = AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedCoursesNewRoute = AuthenticatedCoursesNewRouteImport.update({
    id: '/courses/new',
    path: '/courses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedCourseCourseIdIndexRoute = AuthenticatedCourseCourseIdIndexRouteImport.update({
    id: '/course/$courseId/',
    path: '/course/$courseId/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedCourseCourseIdLessonLessonIdRoute = AuthenticatedCourseCourseIdLessonLessonIdRouteImport.update({
    id: '/course/$courseId/lesson/$lessonId',
    path: '/course/$courseId/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedRouteRouteChildren = {
    AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
    AuthenticatedGithubRoute: AuthenticatedGithubRoute,
    AuthenticatedNotesRoute: AuthenticatedNotesRoute,
    AuthenticatedProfileRoute: AuthenticatedProfileRoute,
    AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
    AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
    AuthenticatedCoursesNewRoute: AuthenticatedCoursesNewRoute,
    AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
    AuthenticatedCourseCourseIdIndexRoute: AuthenticatedCourseCourseIdIndexRoute,
    AuthenticatedCourseCourseIdLessonLessonIdRoute: AuthenticatedCourseCourseIdLessonLessonIdRoute,
};
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
    AuthRoute: AuthRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
